import { chromium } from '@playwright/test';
const URL = 'http://localhost:8765';
const b = await chromium.launch({ headless: true, args: ['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist','--no-sandbox','--disable-setuid-sandbox'] });
const ctx = await b.newContext({ viewport: { width: 1280, height: 720 } });
const pg = await ctx.newPage();
const lines = [];
pg.on('console', (m) => lines.push('[' + m.type() + '] ' + m.text()));
pg.on('pageerror', (e) => lines.push('[PAGEERROR] ' + e.message));
pg.on('requestfailed', (r) => lines.push('[REQFAIL] ' + r.url() + ' ' + (r.failure() || {}).errorText));
const resp = [];
pg.on('response', (r) => resp.push(r.status() + ' ' + r.url()));
await pg.goto(URL, { waitUntil: 'load' });
await new Promise((r) => setTimeout(r, 25000));
const pckRes = resp.filter((u) => u.includes('pck') || u.includes('wasm') || u.includes('js'));
console.log('=== responses (pck/wasm/js) ===');
pckRes.forEach((u) => console.log(u));
console.log('=== console lines ===');
lines.forEach((l) => console.log(l.slice(0, 400)));
await pg.screenshot({ path: 'tests/e2e/screenshots/m5-boot-diag.png' });
await b.close();
